server:
  port: 10000
  
spring:
  application:
    name: tensquare-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/CodingWithPatience/tensquare-config.git   # github上git仓库名称
          skip-ssl-validation: true
          
  devtools:
    restart:
      enabled: false
      
  rabbitmq:
    host: 192.168.254.128
    port: 5672
    
management:          #暴露触发消息总线的地址
  endpoints:
    web:
      exposure:
        include: bus-refresh